name: "publish"

on:
  push:
    branches: [master]
    # tags:
    #   - 'v*'
    paths-ignore:
      - ".idea/**"
      - ".gitattributes"
      - ".github/**.json"
      - ".gitignore"
      - ".gitmodules"
      - "**.md"
      - "**/*.txt"
      - "**/*.png"
      - "**/*.jpg"
      - "LICENSE"
      - "NOTICE"
  workflow_dispatch:

jobs:
  # 创建并获取 release-id
  get-release-id:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    # outputs关键字用于定义一个步骤的输出，允许该步骤将数据传递给工作流中的其他步骤
    outputs:
      # 获取 id 为 id 的脚本的返回值
      release_id: ${{ steps.id.outputs.result }}

    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 设置 Node 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 获取版本号
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: 获取 Release Id
        id: id
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${process.env.PACKAGE_VERSION}`,
              name: `桌面 App v${process.env.PACKAGE_VERSION}`,
              body: '图片压缩程序',
              draft: true,
              prerelease: false
            })
            return data.id

  # 构建 Tauri
  build-tauri:
    needs: get-release-id
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 设置 Node 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@stable

      - name: 安装依赖 (只有 ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: 安装前端依赖
        run: pnpm install

      # 会自动生成补丁文件 latest.json
      - name: 构建 Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.get-release-id.outputs.release_id }}

      - name: 查看打包好的文件
        run: ls -R ./

  # 发布 Release
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    needs: [get-release-id, build-tauri]

    steps:
      - name: 发布 Release
        id: publish-release
        uses: actions/github-script@v7
        env:
          release_id: ${{ needs.get-release-id.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })

  # 生成静态资源并将其推送到 github pages
  updater:
    runs-on: ubuntu-latest
    needs: [get-release-id, build-tauri, publish-release]

    steps:
      - name: 设置 Node 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/checkout@v4
      - run: pnpm i
      - run: pnpm run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 部署 install.json 到 Github Pages 中
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./updater
          # 允许您仅使用最新的提交来创建发布分支
          force_orphan: true
