# 文章：https://juejin.cn/post/7324258006396878883
# Sign Android release 地址：https://github.com/marketplace/actions/sign-android-release
name: Release

on:
  push:
    branches: [master]
    paths-ignore:
      - ".idea/**"
      - ".gitattributes"
      - ".github/**.json"
      - ".gitignore"
      - ".gitmodules"
      - "**.md"
      - "**/*.txt"
      - "**/*.png"
      - "**/*.jpg"
      - "LICENSE"
      - "NOTICE"
      - image/**

    # tags:
    #   - "v*"
    # 忽略的标签类型，不触发构建流程(和tags不能同时写)
    # tags-ignore:
    #   - "d*"

  # strategy:
  # 矩阵使用: ${{ matrix.os }}
  # 下面两个矩阵，会代码就会执行 2 * 3 = 6次
  # matrix:
  #  os: [ubuntu-16.04, ubuntu-18.04]
  #  node: [6, 8, 10]

# 一次持续集成的运行，可以完成多个任务(下面就build)
jobs:
  builds:
    # 构建的系统(ubuntu、windows、macos)
    runs-on: ubuntu-latest

    # 可以依赖其他job
    # needs: xxxJob、[job1, job2]

    # 构建权限，ncipollo/release-action需要使用
    permissions:
      contents: write

    # 操作步骤(按顺序执行)
    steps:
      # 拉取仓库代码
      - name: 签出文件
        uses: actions/checkout@v4

      # 设置Java运行环境(temurin是开源jdk)，可以设置为: 1.8
      - name: 设置 Java 环境
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 设置gradle环境(比如: 6.5)、打包命令
      - name: 设置 Gradle 环境
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleRelease

      # 签名apk
      - name: 签名 APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        # 还能设置build-tools version，29.0.3好像不支持了
        # build-tools可能不存在，用step查看下支持哪些
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - run: ls /usr/local/lib/android/sdk/build-tools/

        # GITHUB_REF_NAME 是 "触发workflow的分支或tag名称"
        name: 重命名文件并移动
      - run: |
          mv ${{steps.sign_app.outputs.signedReleaseFile}} tool_$GITHUB_REF_NAME.apk
          ls -R ./*.apk
        # 可以指定shell命令的执行目录
        # working-directory: ./temp
        # 只当shell的类型
        # shell: bash

      - name: 发布
        uses: softprops/action-gh-release@v1
        # 403 错误 设置 Action 权限 github -> setting -> actiong -> general -> Workflow permissions
        with:
          generate_release_notes: true
          tag_name: ${{ github.repository }}
          body: ${{ github.event.head_commit.message }}
          token: ${{ github.token }}
          files: |
            *.apk

#        name: 发布
#      - uses: ncipollo/release-action@v1.13.0
#        with:
#          # 要包含到Release Assets中的文件
#          artifacts: "*.apk"
#          # 会使用一个临时的 token 来创建 Release
#          token: ${{ github.token }}
#          tag: 1.0.0
#          # 自动生成一些变化列表之类的内容。
#          generateReleaseNotes: true
